// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * Package containing the data models for ComputeDisk.
 * Compute Client.
 */
package com.azure.resourcemanager.compute.disk.models;
