// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute.compute.implementation;

import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.compute.compute.fluent.LogAnalyticsClient;
import com.azure.resourcemanager.compute.compute.fluent.models.LogAnalyticsOperationResultInner;
import com.azure.resourcemanager.compute.compute.models.LogAnalytics;
import com.azure.resourcemanager.compute.compute.models.LogAnalyticsOperationResult;
import com.azure.resourcemanager.compute.compute.models.RequestRateByIntervalInput;
import com.azure.resourcemanager.compute.compute.models.ThrottledRequestsInput;

public final class LogAnalyticsImpl implements LogAnalytics {
    private static final ClientLogger LOGGER = new ClientLogger(LogAnalyticsImpl.class);

    private final LogAnalyticsClient innerClient;

    private final com.azure.resourcemanager.compute.compute.ComputeManager serviceManager;

    public LogAnalyticsImpl(LogAnalyticsClient innerClient,
        com.azure.resourcemanager.compute.compute.ComputeManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public LogAnalyticsOperationResult exportRequestRateByInterval(String location,
        RequestRateByIntervalInput parameters) {
        LogAnalyticsOperationResultInner inner = this.serviceClient().exportRequestRateByInterval(location, parameters);
        if (inner != null) {
            return new LogAnalyticsOperationResultImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public LogAnalyticsOperationResult exportRequestRateByInterval(String location,
        RequestRateByIntervalInput parameters, Context context) {
        LogAnalyticsOperationResultInner inner
            = this.serviceClient().exportRequestRateByInterval(location, parameters, context);
        if (inner != null) {
            return new LogAnalyticsOperationResultImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public LogAnalyticsOperationResult exportThrottledRequests(String location, ThrottledRequestsInput parameters) {
        LogAnalyticsOperationResultInner inner = this.serviceClient().exportThrottledRequests(location, parameters);
        if (inner != null) {
            return new LogAnalyticsOperationResultImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public LogAnalyticsOperationResult exportThrottledRequests(String location, ThrottledRequestsInput parameters,
        Context context) {
        LogAnalyticsOperationResultInner inner
            = this.serviceClient().exportThrottledRequests(location, parameters, context);
        if (inner != null) {
            return new LogAnalyticsOperationResultImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    private LogAnalyticsClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.resourcemanager.compute.compute.ComputeManager manager() {
        return this.serviceManager;
    }
}
