// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute.compute.implementation;

import com.azure.resourcemanager.compute.compute.fluent.models.RunCommandResultInner;
import com.azure.resourcemanager.compute.compute.models.InstanceViewStatus;
import com.azure.resourcemanager.compute.compute.models.RunCommandResult;
import java.util.Collections;
import java.util.List;

public final class RunCommandResultImpl implements RunCommandResult {
    private RunCommandResultInner innerObject;

    private final com.azure.resourcemanager.compute.compute.ComputeManager serviceManager;

    RunCommandResultImpl(RunCommandResultInner innerObject,
        com.azure.resourcemanager.compute.compute.ComputeManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public List<InstanceViewStatus> value() {
        List<InstanceViewStatus> inner = this.innerModel().value();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public RunCommandResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.compute.compute.ComputeManager manager() {
        return this.serviceManager;
    }
}
