// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute.compute.implementation;

import com.azure.resourcemanager.compute.compute.fluent.models.StorageProfileInner;
import com.azure.resourcemanager.compute.compute.models.DataDisk;
import com.azure.resourcemanager.compute.compute.models.DiskControllerTypes;
import com.azure.resourcemanager.compute.compute.models.ImageReference;
import com.azure.resourcemanager.compute.compute.models.OSDisk;
import com.azure.resourcemanager.compute.compute.models.StorageProfile;
import java.util.Collections;
import java.util.List;

public final class StorageProfileImpl implements StorageProfile {
    private StorageProfileInner innerObject;

    private final com.azure.resourcemanager.compute.compute.ComputeManager serviceManager;

    StorageProfileImpl(StorageProfileInner innerObject,
        com.azure.resourcemanager.compute.compute.ComputeManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public ImageReference imageReference() {
        return this.innerModel().imageReference();
    }

    public OSDisk osDisk() {
        return this.innerModel().osDisk();
    }

    public List<DataDisk> dataDisks() {
        List<DataDisk> inner = this.innerModel().dataDisks();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public DiskControllerTypes diskControllerType() {
        return this.innerModel().diskControllerType();
    }

    public Boolean alignRegionalDisksToVMZone() {
        return this.innerModel().alignRegionalDisksToVMZone();
    }

    public StorageProfileInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.compute.compute.ComputeManager manager() {
        return this.serviceManager;
    }
}
