// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute.compute.implementation;

import com.azure.core.management.SubResource;
import com.azure.resourcemanager.compute.compute.fluent.models.StorageProfileInner;
import com.azure.resourcemanager.compute.compute.fluent.models.VirtualMachineScaleSetVMInstanceViewInner;
import com.azure.resourcemanager.compute.compute.fluent.models.VirtualMachineScaleSetVMPropertiesInner;
import com.azure.resourcemanager.compute.compute.models.AdditionalCapabilities;
import com.azure.resourcemanager.compute.compute.models.DiagnosticsProfile;
import com.azure.resourcemanager.compute.compute.models.HardwareProfile;
import com.azure.resourcemanager.compute.compute.models.NetworkProfile;
import com.azure.resourcemanager.compute.compute.models.OSProfile;
import com.azure.resourcemanager.compute.compute.models.ResilientVMDeletionStatus;
import com.azure.resourcemanager.compute.compute.models.SecurityProfile;
import com.azure.resourcemanager.compute.compute.models.StorageProfile;
import com.azure.resourcemanager.compute.compute.models.VirtualMachineScaleSetVMInstanceView;
import com.azure.resourcemanager.compute.compute.models.VirtualMachineScaleSetVMNetworkProfileConfiguration;
import com.azure.resourcemanager.compute.compute.models.VirtualMachineScaleSetVMProperties;
import com.azure.resourcemanager.compute.compute.models.VirtualMachineScaleSetVMProtectionPolicy;
import java.time.OffsetDateTime;

public final class VirtualMachineScaleSetVMPropertiesImpl implements VirtualMachineScaleSetVMProperties {
    private VirtualMachineScaleSetVMPropertiesInner innerObject;

    private final com.azure.resourcemanager.compute.compute.ComputeManager serviceManager;

    VirtualMachineScaleSetVMPropertiesImpl(VirtualMachineScaleSetVMPropertiesInner innerObject,
        com.azure.resourcemanager.compute.compute.ComputeManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public Boolean latestModelApplied() {
        return this.innerModel().latestModelApplied();
    }

    public String vmId() {
        return this.innerModel().vmId();
    }

    public VirtualMachineScaleSetVMInstanceView instanceView() {
        VirtualMachineScaleSetVMInstanceViewInner inner = this.innerModel().instanceView();
        if (inner != null) {
            return new VirtualMachineScaleSetVMInstanceViewImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public HardwareProfile hardwareProfile() {
        return this.innerModel().hardwareProfile();
    }

    public ResilientVMDeletionStatus resilientVMDeletionStatus() {
        return this.innerModel().resilientVMDeletionStatus();
    }

    public StorageProfile storageProfile() {
        StorageProfileInner inner = this.innerModel().storageProfile();
        if (inner != null) {
            return new StorageProfileImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public AdditionalCapabilities additionalCapabilities() {
        return this.innerModel().additionalCapabilities();
    }

    public OSProfile osProfile() {
        return this.innerModel().osProfile();
    }

    public SecurityProfile securityProfile() {
        return this.innerModel().securityProfile();
    }

    public NetworkProfile networkProfile() {
        return this.innerModel().networkProfile();
    }

    public VirtualMachineScaleSetVMNetworkProfileConfiguration networkProfileConfiguration() {
        return this.innerModel().networkProfileConfiguration();
    }

    public DiagnosticsProfile diagnosticsProfile() {
        return this.innerModel().diagnosticsProfile();
    }

    public SubResource availabilitySet() {
        return this.innerModel().availabilitySet();
    }

    public String provisioningState() {
        return this.innerModel().provisioningState();
    }

    public String licenseType() {
        return this.innerModel().licenseType();
    }

    public String modelDefinitionApplied() {
        return this.innerModel().modelDefinitionApplied();
    }

    public VirtualMachineScaleSetVMProtectionPolicy protectionPolicy() {
        return this.innerModel().protectionPolicy();
    }

    public String userData() {
        return this.innerModel().userData();
    }

    public OffsetDateTime timeCreated() {
        return this.innerModel().timeCreated();
    }

    public VirtualMachineScaleSetVMPropertiesInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.compute.compute.ComputeManager manager() {
        return this.serviceManager;
    }
}
