// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.app.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.http.HttpHeaderName;
import com.azure.core.http.HttpHeaders;
import java.util.UUID;

/**
 * The AlertProcessingRulesUpdateHeaders model.
 */
@Fluent
public final class AlertProcessingRulesUpdateHeaders {
    /*
     * The x-ms-request-id property.
     */
    private UUID xMsRequestId;

    // HttpHeaders containing the raw property values.
    /**
     * Creates an instance of AlertProcessingRulesUpdateHeaders class.
     * 
     * @param rawHeaders The raw HttpHeaders that will be used to create the property values.
     */
    public AlertProcessingRulesUpdateHeaders(HttpHeaders rawHeaders) {
        String xMsRequestId = rawHeaders.getValue(HttpHeaderName.X_MS_REQUEST_ID);
        if (xMsRequestId != null) {
            this.xMsRequestId = UUID.fromString(xMsRequestId);
        } else {
            this.xMsRequestId = null;
        }
    }

    /**
     * Get the xMsRequestId property: The x-ms-request-id property.
     * 
     * @return the xMsRequestId value.
     */
    public UUID xMsRequestId() {
        return this.xMsRequestId;
    }

    /**
     * Set the xMsRequestId property: The x-ms-request-id property.
     * 
     * @param xMsRequestId the xMsRequestId value to set.
     * @return the AlertProcessingRulesUpdateHeaders object itself.
     */
    public AlertProcessingRulesUpdateHeaders withXMsRequestId(UUID xMsRequestId) {
        this.xMsRequestId = xMsRequestId;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
