// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

/**
 * Package containing the inner data models for AzureAlertsManagementServiceResourceProvider.
 * APIs for Azure alert processing rules CRUD operations.
 */
package com.azure.app.fluent.models;
