// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

module com.azure.resourcemanager.compute.compute {
    requires transitive com.azure.core.management;

    exports com.azure.resourcemanager.compute.compute;
    exports com.azure.resourcemanager.compute.compute.fluent;
    exports com.azure.resourcemanager.compute.compute.fluent.models;
    exports com.azure.resourcemanager.compute.compute.models;

    opens com.azure.resourcemanager.compute.compute.fluent.models to com.azure.core;
    opens com.azure.resourcemanager.compute.compute.models to com.azure.core;
}
