// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

module com.azure.resourcemanager.compute.disk {
    requires transitive com.azure.core.management;

    exports com.azure.resourcemanager.compute.disk;
    exports com.azure.resourcemanager.compute.disk.fluent;
    exports com.azure.resourcemanager.compute.disk.fluent.models;
    exports com.azure.resourcemanager.compute.disk.models;

    opens com.azure.resourcemanager.compute.disk.fluent.models to com.azure.core;
    opens com.azure.resourcemanager.compute.disk.models to com.azure.core;
    opens com.azure.resourcemanager.compute.disk.implementation.models to com.azure.core;
}
