// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

module com.azure.app {
    requires transitive com.azure.core.management;

    exports com.azure.app;
    exports com.azure.app.fluent;
    exports com.azure.app.fluent.models;
    exports com.azure.app.models;

    opens com.azure.app.fluent.models to com.azure.core;
    opens com.azure.app.models to com.azure.core;
}
