// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute.compute;

import com.azure.core.credential.TokenCredential;
import com.azure.core.http.HttpClient;
import com.azure.core.http.HttpPipeline;
import com.azure.core.http.HttpPipelineBuilder;
import com.azure.core.http.HttpPipelinePosition;
import com.azure.core.http.policy.AddDatePolicy;
import com.azure.core.http.policy.AddHeadersFromContextPolicy;
import com.azure.core.http.policy.BearerTokenAuthenticationPolicy;
import com.azure.core.http.policy.HttpLogOptions;
import com.azure.core.http.policy.HttpLoggingPolicy;
import com.azure.core.http.policy.HttpPipelinePolicy;
import com.azure.core.http.policy.HttpPolicyProviders;
import com.azure.core.http.policy.RequestIdPolicy;
import com.azure.core.http.policy.RetryOptions;
import com.azure.core.http.policy.RetryPolicy;
import com.azure.core.http.policy.UserAgentPolicy;
import com.azure.core.management.profile.AzureProfile;
import com.azure.core.util.Configuration;
import com.azure.core.util.CoreUtils;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.compute.compute.fluent.AzureComputeResourceManagementApi;
import com.azure.resourcemanager.compute.compute.implementation.AvailabilitySetsImpl;
import com.azure.resourcemanager.compute.compute.implementation.AzureComputeResourceManagementApiBuilder;
import com.azure.resourcemanager.compute.compute.implementation.CapacityReservationGroupsImpl;
import com.azure.resourcemanager.compute.compute.implementation.CapacityReservationsImpl;
import com.azure.resourcemanager.compute.compute.implementation.DedicatedHostGroupsImpl;
import com.azure.resourcemanager.compute.compute.implementation.DedicatedHostsImpl;
import com.azure.resourcemanager.compute.compute.implementation.ImagesImpl;
import com.azure.resourcemanager.compute.compute.implementation.LogAnalyticsImpl;
import com.azure.resourcemanager.compute.compute.implementation.OperationsImpl;
import com.azure.resourcemanager.compute.compute.implementation.ProximityPlacementGroupsImpl;
import com.azure.resourcemanager.compute.compute.implementation.RestorePointCollectionsImpl;
import com.azure.resourcemanager.compute.compute.implementation.RestorePointsImpl;
import com.azure.resourcemanager.compute.compute.implementation.SshPublicKeysImpl;
import com.azure.resourcemanager.compute.compute.implementation.UsagesImpl;
import com.azure.resourcemanager.compute.compute.implementation.VirtualMachineExtensionImagesImpl;
import com.azure.resourcemanager.compute.compute.implementation.VirtualMachineExtensionsImpl;
import com.azure.resourcemanager.compute.compute.implementation.VirtualMachineImagesEdgeZonesImpl;
import com.azure.resourcemanager.compute.compute.implementation.VirtualMachineImagesImpl;
import com.azure.resourcemanager.compute.compute.implementation.VirtualMachineRunCommandsImpl;
import com.azure.resourcemanager.compute.compute.implementation.VirtualMachineScaleSetExtensionsImpl;
import com.azure.resourcemanager.compute.compute.implementation.VirtualMachineScaleSetRollingUpgradesImpl;
import com.azure.resourcemanager.compute.compute.implementation.VirtualMachineScaleSetVMExtensionsImpl;
import com.azure.resourcemanager.compute.compute.implementation.VirtualMachineScaleSetVMRunCommandsImpl;
import com.azure.resourcemanager.compute.compute.implementation.VirtualMachineScaleSetVMsImpl;
import com.azure.resourcemanager.compute.compute.implementation.VirtualMachineScaleSetsImpl;
import com.azure.resourcemanager.compute.compute.implementation.VirtualMachineSizesImpl;
import com.azure.resourcemanager.compute.compute.implementation.VirtualMachinesImpl;
import com.azure.resourcemanager.compute.compute.models.AvailabilitySets;
import com.azure.resourcemanager.compute.compute.models.CapacityReservationGroups;
import com.azure.resourcemanager.compute.compute.models.CapacityReservations;
import com.azure.resourcemanager.compute.compute.models.DedicatedHostGroups;
import com.azure.resourcemanager.compute.compute.models.DedicatedHosts;
import com.azure.resourcemanager.compute.compute.models.Images;
import com.azure.resourcemanager.compute.compute.models.LogAnalytics;
import com.azure.resourcemanager.compute.compute.models.Operations;
import com.azure.resourcemanager.compute.compute.models.ProximityPlacementGroups;
import com.azure.resourcemanager.compute.compute.models.RestorePointCollections;
import com.azure.resourcemanager.compute.compute.models.RestorePoints;
import com.azure.resourcemanager.compute.compute.models.SshPublicKeys;
import com.azure.resourcemanager.compute.compute.models.Usages;
import com.azure.resourcemanager.compute.compute.models.VirtualMachineExtensionImages;
import com.azure.resourcemanager.compute.compute.models.VirtualMachineExtensions;
import com.azure.resourcemanager.compute.compute.models.VirtualMachineImages;
import com.azure.resourcemanager.compute.compute.models.VirtualMachineImagesEdgeZones;
import com.azure.resourcemanager.compute.compute.models.VirtualMachineRunCommands;
import com.azure.resourcemanager.compute.compute.models.VirtualMachineScaleSetExtensions;
import com.azure.resourcemanager.compute.compute.models.VirtualMachineScaleSetRollingUpgrades;
import com.azure.resourcemanager.compute.compute.models.VirtualMachineScaleSetVMExtensions;
import com.azure.resourcemanager.compute.compute.models.VirtualMachineScaleSetVMRunCommands;
import com.azure.resourcemanager.compute.compute.models.VirtualMachineScaleSetVMs;
import com.azure.resourcemanager.compute.compute.models.VirtualMachineScaleSets;
import com.azure.resourcemanager.compute.compute.models.VirtualMachineSizes;
import com.azure.resourcemanager.compute.compute.models.VirtualMachines;
import java.time.Duration;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 * Entry point to ComputeManager.
 * Compute Client.
 */
public final class ComputeManager {
    private Operations operations;

    private AvailabilitySets availabilitySets;

    private CapacityReservationGroups capacityReservationGroups;

    private DedicatedHostGroups dedicatedHostGroups;

    private Images images;

    private VirtualMachineImagesEdgeZones virtualMachineImagesEdgeZones;

    private VirtualMachineImages virtualMachineImages;

    private LogAnalytics logAnalytics;

    private VirtualMachineExtensionImages virtualMachineExtensionImages;

    private VirtualMachineRunCommands virtualMachineRunCommands;

    private Usages usages;

    private VirtualMachineScaleSets virtualMachineScaleSets;

    private VirtualMachines virtualMachines;

    private VirtualMachineSizes virtualMachineSizes;

    private ProximityPlacementGroups proximityPlacementGroups;

    private RestorePointCollections restorePointCollections;

    private SshPublicKeys sshPublicKeys;

    private CapacityReservations capacityReservations;

    private DedicatedHosts dedicatedHosts;

    private RestorePoints restorePoints;

    private VirtualMachineScaleSetRollingUpgrades virtualMachineScaleSetRollingUpgrades;

    private VirtualMachineScaleSetExtensions virtualMachineScaleSetExtensions;

    private VirtualMachineScaleSetVMs virtualMachineScaleSetVMs;

    private VirtualMachineScaleSetVMExtensions virtualMachineScaleSetVMExtensions;

    private VirtualMachineScaleSetVMRunCommands virtualMachineScaleSetVMRunCommands;

    private VirtualMachineExtensions virtualMachineExtensions;

    private final AzureComputeResourceManagementApi clientObject;

    private ComputeManager(HttpPipeline httpPipeline, AzureProfile profile, Duration defaultPollInterval) {
        Objects.requireNonNull(httpPipeline, "'httpPipeline' cannot be null.");
        Objects.requireNonNull(profile, "'profile' cannot be null.");
        this.clientObject = new AzureComputeResourceManagementApiBuilder().pipeline(httpPipeline)
            .endpoint(profile.getEnvironment().getResourceManagerEndpoint())
            .subscriptionId(profile.getSubscriptionId())
            .defaultPollInterval(defaultPollInterval)
            .buildClient();
    }

    /**
     * Creates an instance of Compute service API entry point.
     * 
     * @param credential the credential to use.
     * @param profile the Azure profile for client.
     * @return the Compute service API instance.
     */
    public static ComputeManager authenticate(TokenCredential credential, AzureProfile profile) {
        Objects.requireNonNull(credential, "'credential' cannot be null.");
        Objects.requireNonNull(profile, "'profile' cannot be null.");
        return configure().authenticate(credential, profile);
    }

    /**
     * Creates an instance of Compute service API entry point.
     * 
     * @param httpPipeline the {@link HttpPipeline} configured with Azure authentication credential.
     * @param profile the Azure profile for client.
     * @return the Compute service API instance.
     */
    public static ComputeManager authenticate(HttpPipeline httpPipeline, AzureProfile profile) {
        Objects.requireNonNull(httpPipeline, "'httpPipeline' cannot be null.");
        Objects.requireNonNull(profile, "'profile' cannot be null.");
        return new ComputeManager(httpPipeline, profile, null);
    }

    /**
     * Gets a Configurable instance that can be used to create ComputeManager with optional configuration.
     * 
     * @return the Configurable instance allowing configurations.
     */
    public static Configurable configure() {
        return new ComputeManager.Configurable();
    }

    /**
     * The Configurable allowing configurations to be set.
     */
    public static final class Configurable {
        private static final ClientLogger LOGGER = new ClientLogger(Configurable.class);
        private static final String SDK_VERSION = "version";
        private static final Map<String, String> PROPERTIES
            = CoreUtils.getProperties("azure-resourcemanager-compute-compute.properties");

        private HttpClient httpClient;
        private HttpLogOptions httpLogOptions;
        private final List<HttpPipelinePolicy> policies = new ArrayList<>();
        private final List<String> scopes = new ArrayList<>();
        private RetryPolicy retryPolicy;
        private RetryOptions retryOptions;
        private Duration defaultPollInterval;

        private Configurable() {
        }

        /**
         * Sets the http client.
         *
         * @param httpClient the HTTP client.
         * @return the configurable object itself.
         */
        public Configurable withHttpClient(HttpClient httpClient) {
            this.httpClient = Objects.requireNonNull(httpClient, "'httpClient' cannot be null.");
            return this;
        }

        /**
         * Sets the logging options to the HTTP pipeline.
         *
         * @param httpLogOptions the HTTP log options.
         * @return the configurable object itself.
         */
        public Configurable withLogOptions(HttpLogOptions httpLogOptions) {
            this.httpLogOptions = Objects.requireNonNull(httpLogOptions, "'httpLogOptions' cannot be null.");
            return this;
        }

        /**
         * Adds the pipeline policy to the HTTP pipeline.
         *
         * @param policy the HTTP pipeline policy.
         * @return the configurable object itself.
         */
        public Configurable withPolicy(HttpPipelinePolicy policy) {
            this.policies.add(Objects.requireNonNull(policy, "'policy' cannot be null."));
            return this;
        }

        /**
         * Adds the scope to permission sets.
         *
         * @param scope the scope.
         * @return the configurable object itself.
         */
        public Configurable withScope(String scope) {
            this.scopes.add(Objects.requireNonNull(scope, "'scope' cannot be null."));
            return this;
        }

        /**
         * Sets the retry policy to the HTTP pipeline.
         *
         * @param retryPolicy the HTTP pipeline retry policy.
         * @return the configurable object itself.
         */
        public Configurable withRetryPolicy(RetryPolicy retryPolicy) {
            this.retryPolicy = Objects.requireNonNull(retryPolicy, "'retryPolicy' cannot be null.");
            return this;
        }

        /**
         * Sets the retry options for the HTTP pipeline retry policy.
         * <p>
         * This setting has no effect, if retry policy is set via {@link #withRetryPolicy(RetryPolicy)}.
         *
         * @param retryOptions the retry options for the HTTP pipeline retry policy.
         * @return the configurable object itself.
         */
        public Configurable withRetryOptions(RetryOptions retryOptions) {
            this.retryOptions = Objects.requireNonNull(retryOptions, "'retryOptions' cannot be null.");
            return this;
        }

        /**
         * Sets the default poll interval, used when service does not provide "Retry-After" header.
         *
         * @param defaultPollInterval the default poll interval.
         * @return the configurable object itself.
         */
        public Configurable withDefaultPollInterval(Duration defaultPollInterval) {
            this.defaultPollInterval
                = Objects.requireNonNull(defaultPollInterval, "'defaultPollInterval' cannot be null.");
            if (this.defaultPollInterval.isNegative()) {
                throw LOGGER
                    .logExceptionAsError(new IllegalArgumentException("'defaultPollInterval' cannot be negative"));
            }
            return this;
        }

        /**
         * Creates an instance of Compute service API entry point.
         *
         * @param credential the credential to use.
         * @param profile the Azure profile for client.
         * @return the Compute service API instance.
         */
        public ComputeManager authenticate(TokenCredential credential, AzureProfile profile) {
            Objects.requireNonNull(credential, "'credential' cannot be null.");
            Objects.requireNonNull(profile, "'profile' cannot be null.");

            String clientVersion = PROPERTIES.getOrDefault(SDK_VERSION, "UnknownVersion");

            StringBuilder userAgentBuilder = new StringBuilder();
            userAgentBuilder.append("azsdk-java")
                .append("-")
                .append("com.azure.resourcemanager.compute.compute")
                .append("/")
                .append(clientVersion);
            if (!Configuration.getGlobalConfiguration().get("AZURE_TELEMETRY_DISABLED", false)) {
                userAgentBuilder.append(" (")
                    .append(Configuration.getGlobalConfiguration().get("java.version"))
                    .append("; ")
                    .append(Configuration.getGlobalConfiguration().get("os.name"))
                    .append("; ")
                    .append(Configuration.getGlobalConfiguration().get("os.version"))
                    .append("; auto-generated)");
            } else {
                userAgentBuilder.append(" (auto-generated)");
            }

            if (scopes.isEmpty()) {
                scopes.add(profile.getEnvironment().getManagementEndpoint() + "/.default");
            }
            if (retryPolicy == null) {
                if (retryOptions != null) {
                    retryPolicy = new RetryPolicy(retryOptions);
                } else {
                    retryPolicy = new RetryPolicy("Retry-After", ChronoUnit.SECONDS);
                }
            }
            List<HttpPipelinePolicy> policies = new ArrayList<>();
            policies.add(new UserAgentPolicy(userAgentBuilder.toString()));
            policies.add(new AddHeadersFromContextPolicy());
            policies.add(new RequestIdPolicy());
            policies.addAll(this.policies.stream()
                .filter(p -> p.getPipelinePosition() == HttpPipelinePosition.PER_CALL)
                .collect(Collectors.toList()));
            HttpPolicyProviders.addBeforeRetryPolicies(policies);
            policies.add(retryPolicy);
            policies.add(new AddDatePolicy());
            policies.add(new BearerTokenAuthenticationPolicy(credential, scopes.toArray(new String[0])));
            policies.addAll(this.policies.stream()
                .filter(p -> p.getPipelinePosition() == HttpPipelinePosition.PER_RETRY)
                .collect(Collectors.toList()));
            HttpPolicyProviders.addAfterRetryPolicies(policies);
            policies.add(new HttpLoggingPolicy(httpLogOptions));
            HttpPipeline httpPipeline = new HttpPipelineBuilder().httpClient(httpClient)
                .policies(policies.toArray(new HttpPipelinePolicy[0]))
                .build();
            return new ComputeManager(httpPipeline, profile, defaultPollInterval);
        }
    }

    /**
     * Gets the resource collection API of Operations.
     * 
     * @return Resource collection API of Operations.
     */
    public Operations operations() {
        if (this.operations == null) {
            this.operations = new OperationsImpl(clientObject.getOperations(), this);
        }
        return operations;
    }

    /**
     * Gets the resource collection API of AvailabilitySets. It manages AvailabilitySet.
     * 
     * @return Resource collection API of AvailabilitySets.
     */
    public AvailabilitySets availabilitySets() {
        if (this.availabilitySets == null) {
            this.availabilitySets = new AvailabilitySetsImpl(clientObject.getAvailabilitySets(), this);
        }
        return availabilitySets;
    }

    /**
     * Gets the resource collection API of CapacityReservationGroups. It manages CapacityReservationGroup.
     * 
     * @return Resource collection API of CapacityReservationGroups.
     */
    public CapacityReservationGroups capacityReservationGroups() {
        if (this.capacityReservationGroups == null) {
            this.capacityReservationGroups
                = new CapacityReservationGroupsImpl(clientObject.getCapacityReservationGroups(), this);
        }
        return capacityReservationGroups;
    }

    /**
     * Gets the resource collection API of DedicatedHostGroups. It manages DedicatedHostGroup.
     * 
     * @return Resource collection API of DedicatedHostGroups.
     */
    public DedicatedHostGroups dedicatedHostGroups() {
        if (this.dedicatedHostGroups == null) {
            this.dedicatedHostGroups = new DedicatedHostGroupsImpl(clientObject.getDedicatedHostGroups(), this);
        }
        return dedicatedHostGroups;
    }

    /**
     * Gets the resource collection API of Images. It manages Image.
     * 
     * @return Resource collection API of Images.
     */
    public Images images() {
        if (this.images == null) {
            this.images = new ImagesImpl(clientObject.getImages(), this);
        }
        return images;
    }

    /**
     * Gets the resource collection API of VirtualMachineImagesEdgeZones.
     * 
     * @return Resource collection API of VirtualMachineImagesEdgeZones.
     */
    public VirtualMachineImagesEdgeZones virtualMachineImagesEdgeZones() {
        if (this.virtualMachineImagesEdgeZones == null) {
            this.virtualMachineImagesEdgeZones
                = new VirtualMachineImagesEdgeZonesImpl(clientObject.getVirtualMachineImagesEdgeZones(), this);
        }
        return virtualMachineImagesEdgeZones;
    }

    /**
     * Gets the resource collection API of VirtualMachineImages.
     * 
     * @return Resource collection API of VirtualMachineImages.
     */
    public VirtualMachineImages virtualMachineImages() {
        if (this.virtualMachineImages == null) {
            this.virtualMachineImages = new VirtualMachineImagesImpl(clientObject.getVirtualMachineImages(), this);
        }
        return virtualMachineImages;
    }

    /**
     * Gets the resource collection API of LogAnalytics.
     * 
     * @return Resource collection API of LogAnalytics.
     */
    public LogAnalytics logAnalytics() {
        if (this.logAnalytics == null) {
            this.logAnalytics = new LogAnalyticsImpl(clientObject.getLogAnalytics(), this);
        }
        return logAnalytics;
    }

    /**
     * Gets the resource collection API of VirtualMachineExtensionImages.
     * 
     * @return Resource collection API of VirtualMachineExtensionImages.
     */
    public VirtualMachineExtensionImages virtualMachineExtensionImages() {
        if (this.virtualMachineExtensionImages == null) {
            this.virtualMachineExtensionImages
                = new VirtualMachineExtensionImagesImpl(clientObject.getVirtualMachineExtensionImages(), this);
        }
        return virtualMachineExtensionImages;
    }

    /**
     * Gets the resource collection API of VirtualMachineRunCommands. It manages VirtualMachineRunCommand.
     * 
     * @return Resource collection API of VirtualMachineRunCommands.
     */
    public VirtualMachineRunCommands virtualMachineRunCommands() {
        if (this.virtualMachineRunCommands == null) {
            this.virtualMachineRunCommands
                = new VirtualMachineRunCommandsImpl(clientObject.getVirtualMachineRunCommands(), this);
        }
        return virtualMachineRunCommands;
    }

    /**
     * Gets the resource collection API of Usages.
     * 
     * @return Resource collection API of Usages.
     */
    public Usages usages() {
        if (this.usages == null) {
            this.usages = new UsagesImpl(clientObject.getUsages(), this);
        }
        return usages;
    }

    /**
     * Gets the resource collection API of VirtualMachineScaleSets. It manages VirtualMachineScaleSet.
     * 
     * @return Resource collection API of VirtualMachineScaleSets.
     */
    public VirtualMachineScaleSets virtualMachineScaleSets() {
        if (this.virtualMachineScaleSets == null) {
            this.virtualMachineScaleSets
                = new VirtualMachineScaleSetsImpl(clientObject.getVirtualMachineScaleSets(), this);
        }
        return virtualMachineScaleSets;
    }

    /**
     * Gets the resource collection API of VirtualMachines. It manages VirtualMachine.
     * 
     * @return Resource collection API of VirtualMachines.
     */
    public VirtualMachines virtualMachines() {
        if (this.virtualMachines == null) {
            this.virtualMachines = new VirtualMachinesImpl(clientObject.getVirtualMachines(), this);
        }
        return virtualMachines;
    }

    /**
     * Gets the resource collection API of VirtualMachineSizes.
     * 
     * @return Resource collection API of VirtualMachineSizes.
     */
    public VirtualMachineSizes virtualMachineSizes() {
        if (this.virtualMachineSizes == null) {
            this.virtualMachineSizes = new VirtualMachineSizesImpl(clientObject.getVirtualMachineSizes(), this);
        }
        return virtualMachineSizes;
    }

    /**
     * Gets the resource collection API of ProximityPlacementGroups. It manages ProximityPlacementGroup.
     * 
     * @return Resource collection API of ProximityPlacementGroups.
     */
    public ProximityPlacementGroups proximityPlacementGroups() {
        if (this.proximityPlacementGroups == null) {
            this.proximityPlacementGroups
                = new ProximityPlacementGroupsImpl(clientObject.getProximityPlacementGroups(), this);
        }
        return proximityPlacementGroups;
    }

    /**
     * Gets the resource collection API of RestorePointCollections. It manages RestorePointCollection.
     * 
     * @return Resource collection API of RestorePointCollections.
     */
    public RestorePointCollections restorePointCollections() {
        if (this.restorePointCollections == null) {
            this.restorePointCollections
                = new RestorePointCollectionsImpl(clientObject.getRestorePointCollections(), this);
        }
        return restorePointCollections;
    }

    /**
     * Gets the resource collection API of SshPublicKeys. It manages SshPublicKeyResource.
     * 
     * @return Resource collection API of SshPublicKeys.
     */
    public SshPublicKeys sshPublicKeys() {
        if (this.sshPublicKeys == null) {
            this.sshPublicKeys = new SshPublicKeysImpl(clientObject.getSshPublicKeys(), this);
        }
        return sshPublicKeys;
    }

    /**
     * Gets the resource collection API of CapacityReservations. It manages CapacityReservation.
     * 
     * @return Resource collection API of CapacityReservations.
     */
    public CapacityReservations capacityReservations() {
        if (this.capacityReservations == null) {
            this.capacityReservations = new CapacityReservationsImpl(clientObject.getCapacityReservations(), this);
        }
        return capacityReservations;
    }

    /**
     * Gets the resource collection API of DedicatedHosts. It manages DedicatedHost.
     * 
     * @return Resource collection API of DedicatedHosts.
     */
    public DedicatedHosts dedicatedHosts() {
        if (this.dedicatedHosts == null) {
            this.dedicatedHosts = new DedicatedHostsImpl(clientObject.getDedicatedHosts(), this);
        }
        return dedicatedHosts;
    }

    /**
     * Gets the resource collection API of RestorePoints. It manages RestorePoint.
     * 
     * @return Resource collection API of RestorePoints.
     */
    public RestorePoints restorePoints() {
        if (this.restorePoints == null) {
            this.restorePoints = new RestorePointsImpl(clientObject.getRestorePoints(), this);
        }
        return restorePoints;
    }

    /**
     * Gets the resource collection API of VirtualMachineScaleSetRollingUpgrades.
     * 
     * @return Resource collection API of VirtualMachineScaleSetRollingUpgrades.
     */
    public VirtualMachineScaleSetRollingUpgrades virtualMachineScaleSetRollingUpgrades() {
        if (this.virtualMachineScaleSetRollingUpgrades == null) {
            this.virtualMachineScaleSetRollingUpgrades = new VirtualMachineScaleSetRollingUpgradesImpl(
                clientObject.getVirtualMachineScaleSetRollingUpgrades(), this);
        }
        return virtualMachineScaleSetRollingUpgrades;
    }

    /**
     * Gets the resource collection API of VirtualMachineScaleSetExtensions. It manages VirtualMachineScaleSetExtension.
     * 
     * @return Resource collection API of VirtualMachineScaleSetExtensions.
     */
    public VirtualMachineScaleSetExtensions virtualMachineScaleSetExtensions() {
        if (this.virtualMachineScaleSetExtensions == null) {
            this.virtualMachineScaleSetExtensions
                = new VirtualMachineScaleSetExtensionsImpl(clientObject.getVirtualMachineScaleSetExtensions(), this);
        }
        return virtualMachineScaleSetExtensions;
    }

    /**
     * Gets the resource collection API of VirtualMachineScaleSetVMs.
     * 
     * @return Resource collection API of VirtualMachineScaleSetVMs.
     */
    public VirtualMachineScaleSetVMs virtualMachineScaleSetVMs() {
        if (this.virtualMachineScaleSetVMs == null) {
            this.virtualMachineScaleSetVMs
                = new VirtualMachineScaleSetVMsImpl(clientObject.getVirtualMachineScaleSetVMs(), this);
        }
        return virtualMachineScaleSetVMs;
    }

    /**
     * Gets the resource collection API of VirtualMachineScaleSetVMExtensions. It manages
     * VirtualMachineScaleSetVMExtension.
     * 
     * @return Resource collection API of VirtualMachineScaleSetVMExtensions.
     */
    public VirtualMachineScaleSetVMExtensions virtualMachineScaleSetVMExtensions() {
        if (this.virtualMachineScaleSetVMExtensions == null) {
            this.virtualMachineScaleSetVMExtensions = new VirtualMachineScaleSetVMExtensionsImpl(
                clientObject.getVirtualMachineScaleSetVMExtensions(), this);
        }
        return virtualMachineScaleSetVMExtensions;
    }

    /**
     * Gets the resource collection API of VirtualMachineScaleSetVMRunCommands.
     * 
     * @return Resource collection API of VirtualMachineScaleSetVMRunCommands.
     */
    public VirtualMachineScaleSetVMRunCommands virtualMachineScaleSetVMRunCommands() {
        if (this.virtualMachineScaleSetVMRunCommands == null) {
            this.virtualMachineScaleSetVMRunCommands = new VirtualMachineScaleSetVMRunCommandsImpl(
                clientObject.getVirtualMachineScaleSetVMRunCommands(), this);
        }
        return virtualMachineScaleSetVMRunCommands;
    }

    /**
     * Gets the resource collection API of VirtualMachineExtensions. It manages VirtualMachineExtension.
     * 
     * @return Resource collection API of VirtualMachineExtensions.
     */
    public VirtualMachineExtensions virtualMachineExtensions() {
        if (this.virtualMachineExtensions == null) {
            this.virtualMachineExtensions
                = new VirtualMachineExtensionsImpl(clientObject.getVirtualMachineExtensions(), this);
        }
        return virtualMachineExtensions;
    }

    /**
     * Gets wrapped service client AzureComputeResourceManagementApi providing direct access to the underlying
     * auto-generated API implementation, based on Azure REST API.
     * 
     * @return Wrapped service client AzureComputeResourceManagementApi.
     */
    public AzureComputeResourceManagementApi serviceClient() {
        return this.clientObject;
    }
}
