// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.compute.disk.implementation;

import com.azure.resourcemanager.compute.disk.fluent.models.AccessUriInner;
import com.azure.resourcemanager.compute.disk.models.AccessUri;

public final class AccessUriImpl implements AccessUri {
    private AccessUriInner innerObject;

    private final com.azure.resourcemanager.compute.disk.ComputeDiskManager serviceManager;

    AccessUriImpl(AccessUriInner innerObject,
        com.azure.resourcemanager.compute.disk.ComputeDiskManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String accessSas() {
        return this.innerModel().accessSas();
    }

    public String securityDataAccessSas() {
        return this.innerModel().securityDataAccessSas();
    }

    public String securityMetadataAccessSas() {
        return this.innerModel().securityMetadataAccessSas();
    }

    public AccessUriInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.compute.disk.ComputeDiskManager manager() {
        return this.serviceManager;
    }
}
