// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.compute.disk.implementation;

import com.azure.core.management.SystemData;
import com.azure.resourcemanager.compute.disk.fluent.models.DiskRestorePointInner;
import com.azure.resourcemanager.compute.disk.models.DiskPurchasePlan;
import com.azure.resourcemanager.compute.disk.models.DiskRestorePoint;
import com.azure.resourcemanager.compute.disk.models.DiskSecurityProfile;
import com.azure.resourcemanager.compute.disk.models.Encryption;
import com.azure.resourcemanager.compute.disk.models.HyperVGeneration;
import com.azure.resourcemanager.compute.disk.models.NetworkAccessPolicy;
import com.azure.resourcemanager.compute.disk.models.OperatingSystemTypes;
import com.azure.resourcemanager.compute.disk.models.PublicNetworkAccess;
import com.azure.resourcemanager.compute.disk.models.SupportedCapabilities;
import java.time.OffsetDateTime;

public final class DiskRestorePointImpl implements DiskRestorePoint {
    private DiskRestorePointInner innerObject;

    private final com.azure.resourcemanager.compute.disk.ComputeDiskManager serviceManager;

    DiskRestorePointImpl(DiskRestorePointInner innerObject,
        com.azure.resourcemanager.compute.disk.ComputeDiskManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public SystemData systemData() {
        return this.innerModel().systemData();
    }

    public OffsetDateTime timeCreated() {
        return this.innerModel().timeCreated();
    }

    public String sourceResourceId() {
        return this.innerModel().sourceResourceId();
    }

    public OperatingSystemTypes osType() {
        return this.innerModel().osType();
    }

    public HyperVGeneration hyperVGeneration() {
        return this.innerModel().hyperVGeneration();
    }

    public DiskPurchasePlan purchasePlan() {
        return this.innerModel().purchasePlan();
    }

    public SupportedCapabilities supportedCapabilities() {
        return this.innerModel().supportedCapabilities();
    }

    public String familyId() {
        return this.innerModel().familyId();
    }

    public String sourceUniqueId() {
        return this.innerModel().sourceUniqueId();
    }

    public Encryption encryption() {
        return this.innerModel().encryption();
    }

    public Boolean supportsHibernation() {
        return this.innerModel().supportsHibernation();
    }

    public NetworkAccessPolicy networkAccessPolicy() {
        return this.innerModel().networkAccessPolicy();
    }

    public PublicNetworkAccess publicNetworkAccess() {
        return this.innerModel().publicNetworkAccess();
    }

    public String diskAccessId() {
        return this.innerModel().diskAccessId();
    }

    public Float completionPercent() {
        return this.innerModel().completionPercent();
    }

    public String replicationState() {
        return this.innerModel().replicationState();
    }

    public String sourceResourceLocation() {
        return this.innerModel().sourceResourceLocation();
    }

    public DiskSecurityProfile securityProfile() {
        return this.innerModel().securityProfile();
    }

    public Integer logicalSectorSize() {
        return this.innerModel().logicalSectorSize();
    }

    public DiskRestorePointInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.compute.disk.ComputeDiskManager manager() {
        return this.serviceManager;
    }
}
