// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.compute.disk.implementation;

import com.azure.core.http.rest.PagedIterable;
import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.SimpleResponse;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.compute.disk.fluent.PrivateEndpointConnectionsClient;
import com.azure.resourcemanager.compute.disk.fluent.models.PrivateEndpointConnectionInner;
import com.azure.resourcemanager.compute.disk.models.PrivateEndpointConnection;
import com.azure.resourcemanager.compute.disk.models.PrivateEndpointConnections;

public final class PrivateEndpointConnectionsImpl implements PrivateEndpointConnections {
    private static final ClientLogger LOGGER = new ClientLogger(PrivateEndpointConnectionsImpl.class);

    private final PrivateEndpointConnectionsClient innerClient;

    private final com.azure.resourcemanager.compute.disk.ComputeDiskManager serviceManager;

    public PrivateEndpointConnectionsImpl(PrivateEndpointConnectionsClient innerClient,
        com.azure.resourcemanager.compute.disk.ComputeDiskManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public Response<PrivateEndpointConnection> getAPrivateEndpointConnectionWithResponse(String resourceGroupName,
        String diskAccessName, String privateEndpointConnectionName, Context context) {
        Response<PrivateEndpointConnectionInner> inner = this.serviceClient()
            .getAPrivateEndpointConnectionWithResponse(resourceGroupName, diskAccessName, privateEndpointConnectionName,
                context);
        if (inner != null) {
            return new SimpleResponse<>(inner.getRequest(), inner.getStatusCode(), inner.getHeaders(),
                new PrivateEndpointConnectionImpl(inner.getValue(), this.manager()));
        } else {
            return null;
        }
    }

    public PrivateEndpointConnection getAPrivateEndpointConnection(String resourceGroupName, String diskAccessName,
        String privateEndpointConnectionName) {
        PrivateEndpointConnectionInner inner = this.serviceClient()
            .getAPrivateEndpointConnection(resourceGroupName, diskAccessName, privateEndpointConnectionName);
        if (inner != null) {
            return new PrivateEndpointConnectionImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public PrivateEndpointConnection updateAPrivateEndpointConnection(String resourceGroupName, String diskAccessName,
        String privateEndpointConnectionName, PrivateEndpointConnectionInner privateEndpointConnection) {
        PrivateEndpointConnectionInner inner = this.serviceClient()
            .updateAPrivateEndpointConnection(resourceGroupName, diskAccessName, privateEndpointConnectionName,
                privateEndpointConnection);
        if (inner != null) {
            return new PrivateEndpointConnectionImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public PrivateEndpointConnection updateAPrivateEndpointConnection(String resourceGroupName, String diskAccessName,
        String privateEndpointConnectionName, PrivateEndpointConnectionInner privateEndpointConnection,
        Context context) {
        PrivateEndpointConnectionInner inner = this.serviceClient()
            .updateAPrivateEndpointConnection(resourceGroupName, diskAccessName, privateEndpointConnectionName,
                privateEndpointConnection, context);
        if (inner != null) {
            return new PrivateEndpointConnectionImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public void deleteAPrivateEndpointConnection(String resourceGroupName, String diskAccessName,
        String privateEndpointConnectionName) {
        this.serviceClient()
            .deleteAPrivateEndpointConnection(resourceGroupName, diskAccessName, privateEndpointConnectionName);
    }

    public void deleteAPrivateEndpointConnection(String resourceGroupName, String diskAccessName,
        String privateEndpointConnectionName, Context context) {
        this.serviceClient()
            .deleteAPrivateEndpointConnection(resourceGroupName, diskAccessName, privateEndpointConnectionName,
                context);
    }

    public PagedIterable<PrivateEndpointConnection> listPrivateEndpointConnections(String resourceGroupName,
        String diskAccessName) {
        PagedIterable<PrivateEndpointConnectionInner> inner
            = this.serviceClient().listPrivateEndpointConnections(resourceGroupName, diskAccessName);
        return ResourceManagerUtils.mapPage(inner, inner1 -> new PrivateEndpointConnectionImpl(inner1, this.manager()));
    }

    public PagedIterable<PrivateEndpointConnection> listPrivateEndpointConnections(String resourceGroupName,
        String diskAccessName, Context context) {
        PagedIterable<PrivateEndpointConnectionInner> inner
            = this.serviceClient().listPrivateEndpointConnections(resourceGroupName, diskAccessName, context);
        return ResourceManagerUtils.mapPage(inner, inner1 -> new PrivateEndpointConnectionImpl(inner1, this.manager()));
    }

    private PrivateEndpointConnectionsClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.resourcemanager.compute.disk.ComputeDiskManager manager() {
        return this.serviceManager;
    }
}
