// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

/**
 * Package containing the inner data models for AzureComputeResourceManagementApi.
 * Compute Client.
 */
package com.azure.resourcemanager.compute.compute.fluent.models;
