// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.compute.disk.fluent;

import com.azure.core.http.HttpPipeline;
import java.time.Duration;

/**
 * The interface for ComputeDiskManagementClient class.
 */
public interface ComputeDiskManagementClient {
    /**
     * Gets Service host.
     * 
     * @return the endpoint value.
     */
    String getEndpoint();

    /**
     * Gets Version parameter.
     * 
     * @return the apiVersion value.
     */
    String getApiVersion();

    /**
     * Gets The ID of the target subscription. The value must be an UUID.
     * 
     * @return the subscriptionId value.
     */
    String getSubscriptionId();

    /**
     * Gets The HTTP pipeline to send requests through.
     * 
     * @return the httpPipeline value.
     */
    HttpPipeline getHttpPipeline();

    /**
     * Gets The default poll interval for long-running operation.
     * 
     * @return the defaultPollInterval value.
     */
    Duration getDefaultPollInterval();

    /**
     * Gets the DisksClient object to access its operations.
     * 
     * @return the DisksClient object.
     */
    DisksClient getDisks();

    /**
     * Gets the DiskAccessesClient object to access its operations.
     * 
     * @return the DiskAccessesClient object.
     */
    DiskAccessesClient getDiskAccesses();

    /**
     * Gets the PrivateEndpointConnectionsClient object to access its operations.
     * 
     * @return the PrivateEndpointConnectionsClient object.
     */
    PrivateEndpointConnectionsClient getPrivateEndpointConnections();

    /**
     * Gets the DiskEncryptionSetsClient object to access its operations.
     * 
     * @return the DiskEncryptionSetsClient object.
     */
    DiskEncryptionSetsClient getDiskEncryptionSets();

    /**
     * Gets the DiskRestorePointsClient object to access its operations.
     * 
     * @return the DiskRestorePointsClient object.
     */
    DiskRestorePointsClient getDiskRestorePoints();

    /**
     * Gets the SnapshotsClient object to access its operations.
     * 
     * @return the SnapshotsClient object.
     */
    SnapshotsClient getSnapshots();
}
